# sley configuration file
# Documentation: https://github.com/indaco/sley

# Enabled plugins:
#   - commit-parser
#   - tag-manager
#   - changelog-generator

path: internal/version/.version

plugins:
  # Analyzes conventional commits to suggest version bumps
  commit-parser: true
  # Manages git tags - use `sley tag create` for manual tagging
  tag-manager:
    enabled: true
  # Generates changelogs from git commits
  changelog-generator:
    enabled: true
    repository:
      auto-detect: true
    exclude-patterns:
      - "^Merge"
      - "^WIP"
      - "^release"
    use-default-icons: true
    contributors:
      enabled: true
extensions:
  - name: version-sync
    path: ./local-extensions/version-sync
    enabled: true
