# sley configuration file
# Documentation: https://github.com/indaco/sley

# Enabled plugins:
#   - commit-parser
#   - tag-manager
#   - changelog-generator

path: internal/version/.version

plugins:
  # Analyzes conventional commits to suggest version bumps
  commit-parser: true
  # Generates changelogs from git commits
  changelog-generator:
    enabled: true
    mode: "versioned"
    changes-dir: ".changes"
    use-default-icons: true
    repository:
      auto-detect: true
    exclude-patterns:
      - "^Merge"
      - "^WIP"
      - "^release"
    contributors:
      enabled: true
