path: internal/version/.version

plugins:
  changelog-generator:
    enabled: true
    mode: "versioned"
    changes-dir: ".changes"
    header-template: ".changes/header.tpl.md"
    repository:
      provider: "github"
      owner: "indaco"
      repo: "sley"
    use-default-icons: true
    exclude-patterns:
      - "^Merge"
      - "^WIP"
      - "^release"
    contributors:
      enabled: true
